/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainsStationIdRouteImport } from './routes/trains.$stationId'

const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainsStationIdRoute = TrainsStationIdRouteImport.update({
  id: '/trains/$stationId',
  path: '/trains/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stations': typeof StationsRoute
  '/trains/$stationId': typeof TrainsStationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stations': typeof StationsRoute
  '/trains/$stationId': typeof TrainsStationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stations': typeof StationsRoute
  '/trains/$stationId': typeof TrainsStationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stations' | '/trains/$stationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stations' | '/trains/$stationId'
  id: '__root__' | '/' | '/stations' | '/trains/$stationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StationsRoute: typeof StationsRoute
  TrainsStationIdRoute: typeof TrainsStationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trains/$stationId': {
      id: '/trains/$stationId'
      path: '/trains/$stationId'
      fullPath: '/trains/$stationId'
      preLoaderRoute: typeof TrainsStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StationsRoute: StationsRoute,
  TrainsStationIdRoute: TrainsStationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
